branch-defaults:
  master:
    environment: TaskitApi-env
deploy:
  artifact: dist/taskit-api.zip
environment-defaults:
  TaskitApi-env:
    branch: null
    repository: null
global:
  application_name: taskit-api
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application