version: 2
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: teovillanueva/node-postgres:0.0.3
        environment:
          DATABASE_URL: postgres://root:toor@localhost:5432/taskit # This is the URL that will be used by prisma
          JWT_SECRET: testest
    steps:
      - run:
          name: Setup PostgreSQL
          command: |
            chmod -R 777 ~
            /etc/init.d/postgresql start
            sudo -u postgres sh -c 'createuser root'
            sudo -u postgres psql -c "CREATE DATABASE taskit;"
            sudo -u postgres psql -c "ALTER USER root CREATEDB"
            sudo -u postgres psql -c "ALTER USER root PASSWORD 'toor';"
            sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE taskit TO root;"
            sudo -u postgres psql -c "GRANT CONNECT ON DATABASE taskit TO root;"
            sudo -u postgres psql -c "CREATE SCHEMA IF NOT EXISTS public AUTHORIZATION root;"
            sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO root;"

      # Checkout the code
      - checkout

      # Resote cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
    
      # Install dependencies
      - run: npm install

      # save cache
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      # Run migrations on test database
      - run: npx prisma migrate up --experimental

      # run tests
      - run: npm test
  
  build:
      working_directory: ~/repo
      docker:
        - image: circleci/node
      steps:
        - run: echo "hello!"

workflows:
  version: 2
  test:
    jobs:
      - test